const exactTextMap: Record<string, string> = {
  "opencow 瀹搞儰缍旈崣?": "opencow 工作台",
  "Ollama 閺堫剙婀存导妯哄帥": "Ollama 本地优先",
  "缁涘绶?Ollama": "等待 Ollama",
  "閺堫亪鈧瀚ㄥΟ鈥崇€?": "未选择模型",
  "閸欘亣顕?": "只读",
  "閺冪姵纭舵潻鐐村复閺堫剙婀?Ollama": "无法连接本地 Ollama",
  "Ollama 閸濆秴绨茬搾鍛閿涘矁顕Λ鈧弻銉︽拱閸︾増膩閸ㄥ濮搁幀浣碘偓?": "Ollama 响应超时，请检查本地模型状态。",
  "濡偓閺?Ollama 閺堝秴濮熼獮鍫曞櫢鐠?": "检查 Ollama 服务并重试",
  "濡剝瀚欓張顒€婀存禒璇插婢惰精瑙?": "模拟本地任务失败",
  "妯℃嫙鏈湴浠诲姟澶辫触": "模拟本地任务失败",
  "閺堫剙婀存禒璇插閹笛嗩攽婢惰精瑙?": "本地任务执行失败",
  "鏈湴浠诲姟鎵ц澶辫触": "本地任务执行失败",
  "閺堫剙婀存禒璇插閹笛嗩攽鐎瑰本鍨?": "本地任务执行完成",
  "閺堫剙婀存禒璇插瀹告彃浠犲?": "本地任务已停止",
  "閸嬫粍顒涙禒璇插": "停止任务",
  "鍋滄浠诲姟": "停止任务",
  "闁插秷鐦張顒€婀存禒璇插": "重试本地任务",
  "瑜版挸澧犳禒璇插瀹歌弓鑵戦弬?": "当前任务已中断",
  "宸叉洿鏂拌仈缃戞悳绱㈡彁渚涙柟": "已更新联网搜索提供方",
  "鑱旂綉鎼滅储 provider 鏇存柊": "联网搜索 provider 更新"
};

const fragmentTextMap: Array<[string, string]> = [
  ["濡€虫健:", "模块:"],
  ["閺夈儲绨?", "来源:"],
  ["閺冨爼妫?", "时间:"],
  ["瀵ら缚顔?", "建议:"],
  ["閺夊啴妾?", "权限:"],
  ["閸ョ偤鈧偓", "回退"],
  ["鑱旂綉鎼滅储灏嗕紭鍏堜娇鐢?", "联网搜索将优先使用 "],
  ["锛屼粛浼氫繚鐣欐潵婧愯褰曚笌瀹¤杩借釜銆?", "，仍会保留来源记录与审计追踪。"],
  ["棰勮鍥為€€鍒?鍚姩鍩虹嚎", "预览回退到 启动基线"]
];

export function normalizeWorkbenchText(value: string): string {
  if (!value) {
    return value;
  }

  let normalized = exactTextMap[value] ?? value;

  for (const [from, to] of fragmentTextMap) {
    normalized = normalized.split(from).join(to);
  }

  return normalized.replace(/\?+/g, "").trim();
}

export function getLocalizedPermissionModeLabel(mode: string): string {
  const normalized = normalizeWorkbenchText(mode).trim();

  if (normalized === "workspace-write") {
    return "工作区读写";
  }

  if (normalized === "controlled-full") {
    return "受控完全访问";
  }

  if (normalized === "readonly") {
    return "只读";
  }

  return normalized;
}

export function getLocalizedPermissionReason(reason: string): string {
  const normalized = normalizeWorkbenchText(reason).trim();

  if (!normalized) {
    return normalized;
  }

  if (/[\u4e00-\u9fff]/.test(normalized)) {
    return normalized;
  }

  if (
    normalized === "Workspace write permission is required before opencow can ask the selected local model to generate an NPC configuration and save it under .opencow/npcs/."
  ) {
    return "需要先授予工作区读写权限，opencow 才能调用当前选中的本地大模型生成 NPC 配置，并保存到 .opencow/npcs/ 目录下。";
  }

  if (normalized === "Workspace write permission is required before launching a matched local project from the desktop assistant.") {
    return "需要先授予工作区读写权限，桌面助手才能启动匹配到的本地项目。";
  }

  if (normalized === "Workspace write permission is required before stopping a matched local project from the desktop assistant.") {
    return "需要先授予工作区读写权限，桌面助手才能停止匹配到的本地项目。";
  }

  return normalized
    .replace(/^Workspace write permission is required before /i, "需要先授予工作区读写权限，才能")
    .replace(/^Controlled full permission is required before /i, "需要先授予受控完全访问权限，才能")
    .replace(/\bopencow can\b/gi, "opencow 可以")
    .replace(/\blaunch the matched local project\b/gi, "启动匹配到的本地项目")
    .replace(/\bcapture a screenshot from the matched local project\b/gi, "为匹配到的本地项目截图")
    .replace(/\bgenerate the showcase site for the matched local project\b/gi, "为匹配到的本地项目生成展示站点")
    .replace(/\bcreate(?:ing)? temp-output\b/gi, "创建 temp-output 目录")
    .replace(/\binstalling a local skill into the workspace skills directory\b/gi, "把本地 Skill 安装到工作区技能目录")
    .replace(/\benabling a local skill in the workspace registry\b/gi, "在工作区注册表中启用本地 Skill")
    .replace(/\bdisabling a local skill in the workspace registry\b/gi, "在工作区注册表中停用本地 Skill")
    .replace(/\brepair its workspace-local enabled skills registry at /gi, "修复工作区内的 enabled skills 注册表：")
    .replace(/\brepair its workspace project runtime registry at /gi, "修复工作区项目运行时注册表：")
    .replace(/\blaunching a matched local project from the desktop assistant\b/gi, "启动匹配到的本地项目")
    .replace(/\bstopping a matched local project from the desktop assistant\b/gi, "停止匹配到的本地项目")
    .replace(/\bstarting a local MCP plugin process\b/gi, "启动本地 MCP 插件进程")
    .replace(/\.$/, "。");
}

export function getLocalizedPermissionRiskSummary(riskSummary: string): string {
  const normalized = normalizeWorkbenchText(riskSummary).trim();

  if (!normalized) {
    return normalized;
  }

  if (/[\u4e00-\u9fff]/.test(normalized)) {
    return normalized;
  }

  if (
    normalized === "This task writes only an NPC configuration JSON file inside .opencow/npcs/. The configuration content must be generated by the selected local model after approval; no fixed template answer is used."
  ) {
    return "这次操作只会在 .opencow/npcs/ 下写入一个 NPC 配置 JSON 文件。配置内容会在你批准后由当前选中的本地大模型生成，并不会套用固定模板回答。";
  }

  if (
    normalized === "This task starts a local workspace project process through a fixed project-run path, keeps execution inside the approved workspace, and must remain audit-visible."
  ) {
    return "这次操作只会通过固定的项目启动链路拉起本地工作区项目，执行范围会保持在已授权工作区内，并保留可审计记录。";
  }

  if (
    normalized === "This task stops only a previously launched local workspace project through a fixed project-stop path, keeps execution inside the approved workspace, and must remain audit-visible."
  ) {
    return "这次操作只会通过固定的项目停止链路结束之前启动的本地工作区项目，执行范围会保持在已授权工作区内，并保留可审计记录。";
  }

  return normalized
    .replace(/^This task launches only the matched local workspace project/gi, "这次操作只会启动匹配到的本地工作区项目")
    .replace(/^This task captures only a task-scoped screenshot artifact/gi, "这次操作只会为当前任务保存一份截图产物")
    .replace(/^This task writes only an NPC configuration JSON file inside \.opencow\/npcs\/\./gi, "这次操作只会在 .opencow/npcs/ 目录下写入一个 NPC 配置 JSON 文件")
    .replace(/^This task rewrites only /gi, "这次操作只会重写 ")
    .replace(/^This task copies an approved local skill /gi, "这次操作只会复制一个已批准的本地 Skill ")
    .replace(/^This task writes only a controlled local skill registry entry inside the approved workspace and does not execute the skill\./gi, "这次操作只会在已授权工作区内写入受控的本地 Skill 注册表条目，不会直接执行该 Skill。")
    .replace(/^This task removes only a controlled local skill registry entry inside the approved workspace and does not execute the skill\./gi, "这次操作只会在已授权工作区内移除受控的本地 Skill 注册表条目，不会直接执行该 Skill。")
    .replace(/^High-risk cleanup must keep permission escalation, confirmation, audit logging, timeout, and rollback protections\./gi, "高风险清理必须保留提权、确认、审计、超时和回退保护。")
    .replace(/^This task starts a local MCP-adjacent plugin process and must keep permission escalation, dangerous confirmation, audit logging, timeout, and rollback-visible protections\./gi, "这次操作会启动本地 MCP 相关插件进程，必须保留提权、高风险确认、审计、超时和可见回退保护。")
    .replace(/\.$/, "。");
}

function isReadonlyShellFailure(value: string): boolean {
  const normalized = value.toLowerCase();

  return normalized.includes("readonly-shell") || normalized.includes("required permission: readonly");
}

function isWorkspaceWriteShellFailure(value: string): boolean {
  const normalized = value.toLowerCase();

  return normalized.includes("workspace-write")
    || normalized.includes("workspace_write")
    || normalized.includes("required permission: workspace-write");
}

function isControlledFullShellFailure(value: string): boolean {
  const normalized = value.toLowerCase();

  return normalized.includes("controlled-full")
    || normalized.includes("controlled_full")
    || normalized.includes("required permission: controlled-full");
}

function isLocalRagFailure(value: string): boolean {
  const normalized = value.toLowerCase();

  return normalized.includes("local rag search failed")
    || normalized.includes("rag retry self-check")
    || normalized.includes("local knowledge index")
    || normalized.includes("document parsers for pptx/docx/md")
    || normalized.includes("pptx/docx/md");
}

function isLocalExecutionMappingFailure(value: string): boolean {
  const normalized = value.toLowerCase();

  return normalized.includes("invalid local assistant execution result")
    || normalized.includes("inspect assistanttaskservice result mapping");
}

function isUnknownLocalExecutionFailure(value: string): boolean {
  return value.toLowerCase().includes("unknown local assistant execution error");
}

function isNpcConfigModelFailure(value: string): boolean {
  return value.toLowerCase().includes("executionkind=npc-config-write");
}

export function isLocalAssistantPlannerFailureSource(source?: string): boolean {
  return source === "local_assistant_planner"
    || source === "local_assistant_self_check_planner"
    || source === "local_task_retry_self_check_planner";
}

export function getVisibleLocalTaskFailureTitle(summary: string, source?: string, detail = ""): string {
  if (isLocalAssistantPlannerFailureSource(source) || summary === "Local assistant planning failed") {
    return "\u672c\u5730\u52a9\u624b\u89c4\u5212\u5931\u8d25";
  }

  if (source === "local_task_attempt_guard") {
    return "本地任务已达到重试上限";
  }

  if (source === "local_task_timeout" || summary === "Local task execution timed out") {
    return summary;
  }

  if (source === "local_model_chat_runner" && (summary === "NPC 配置生成失败" || isNpcConfigModelFailure(detail))) {
    return "NPC 配置生成失败";
  }

  if (
    summary === "Local task execution failed"
    && (isReadonlyShellFailure(detail) || isWorkspaceWriteShellFailure(detail) || isControlledFullShellFailure(detail))
  ) {
    return "本地任务执行失败";
  }

  if (isLocalRagFailure(detail) || isLocalRagFailure(summary)) {
    return "本地 RAG 检索失败";
  }

  if (isLocalExecutionMappingFailure(detail) || isLocalExecutionMappingFailure(summary)) {
    return "本地任务执行失败";
  }

  if (summary === "Local task execution failed" && isUnknownLocalExecutionFailure(detail)) {
    return "本地任务执行失败";
  }

  return normalizeWorkbenchText(summary);
}

export function getVisibleLocalTaskFailureActionLabel(actionLabel: string): string {
  const normalized = actionLabel.trim();

  if (
    normalized.includes("Review planner routing, rewrite the request, or restart from a readonly preview before retrying.")
    || normalized.includes("Review RAG self-check routing before retrying the failed document query.")
    || normalized.includes("Review shell self-check routing before retrying the failed write or destructive command.")
    || normalized.includes("请改写请求后重新提交")
    || normalized.includes("从只读预览重新开始")
  ) {
    return "\u8bf7\u6539\u5199\u8bf7\u6c42\uff0c\u6216\u4ece\u53ea\u8bfb\u9884\u89c8\u91cd\u65b0\u5f00\u59cb\u3002";
  }

  if (
    normalized.includes("verify the readonly shell bridge, workspace root, command whitelist, and audit trail before retrying")
    || normalized.includes("只读 shell 桥接")
  ) {
    return "请先检查只读 shell 桥接、工作区根目录、命令白名单和审计记录，再重试。";
  }

  if (
    normalized.includes("verify the permission approval, workspace root, command whitelist, and audit trail before retrying")
    || normalized.includes("权限审批")
  ) {
    return "请先检查权限审批、工作区根目录、命令白名单和审计记录，再重试。";
  }

  if (
    normalized.includes("verify the dangerous confirmation, rollback snapshot availability, workspace root, command whitelist, and audit trail before retrying")
    || normalized.includes("高风险确认")
  ) {
    return "请先检查高风险确认、回退快照、工作区根目录、命令白名单和审计记录，再重试。";
  }

  if (normalized === "restore snapshot capability or run a readonly preview before retrying destructive execution.") {
    return "请先恢复回退快照能力，或先运行只读预览再重试高风险执行。";
  }

  if (isLocalRagFailure(normalized)) {
    return "请先检查本地 RAG 索引、pptx/docx/md 解析器和工作区根目录，再缩小文档范围重试。";
  }

  if (isLocalExecutionMappingFailure(normalized)) {
    return "请先检查本地助手执行结果映射，再重试。";
  }

  if (normalized === "Check the local execution chain and try again.") {
    return "请检查本地执行链和日志，再重试。";
  }

  return normalizeWorkbenchText(actionLabel);
}

export function getVisibleLocalTaskFailureDetail(detail: string, source?: string): string {
  if (isLocalAssistantPlannerFailureSource(source)) {
    return "\u672c\u5730\u52a9\u624b\u6682\u65f6\u65e0\u6cd5\u7406\u89e3\u8fd9\u6b21\u8bf7\u6c42\uff0c\u672a\u6392\u961f\u3001\u672a\u6267\u884c\u4efb\u4f55\u547d\u4ee4\u3002";
  }

  if (source === "local_model_chat_runner") {
    const actionableDetail = getActionableOllamaFailureDetail(detail);

    if (actionableDetail) {
      return actionableDetail;
    }

    if (isNpcConfigModelFailure(detail) && detail.includes("streamPhase=waiting-first-chunk")) {
      return "本地模型已接到 NPC 配置生成请求，但首轮输出没有在本轮超时前返回；NPC 配置尚未写入，完整模型、输入长度和等待阶段诊断已保留在展开详情中。";
    }

    if (isNpcConfigModelFailure(detail) && detail.includes("streamPhase=streaming")) {
      return "本地模型已经开始生成 NPC 配置，但没有在本轮超时前完整结束；NPC 配置尚未写入，已保留首块耗时和生成阶段诊断，方便缩小需求后重试。";
    }

    if (detail.includes("streamPhase=waiting-first-chunk")) {
      return "本地模型已连接，但首轮输出没有在本轮超时前返回；这通常是模型冷启动、上下文过长或当前模型生成过慢。OpenCow 已终止本轮等待并保留模型、输入长度和等待阶段诊断，重试前会重新检测 Ollama，建议先缩短问题或切换更快模型。";
    }

    if (detail.includes("streamPhase=streaming")) {
      return "本地模型已经开始输出，但没有在本轮超时前完整结束；OpenCow 已保留首块耗时和生成阶段诊断。建议让模型分段继续、减少单次输出范围，或切换更快模型后重试。";
    }

    return "本地模型本轮没有按时返回完整结果，详细诊断已保留在本地任务失败细节和日志中。";
  }

  if (isReadonlyShellFailure(detail)) {
    return "本地 shell 执行没有完成。完整命令、权限和底层错误已保留在日志、回退记录和展开详情中。";
  }

  if (isWorkspaceWriteShellFailure(detail)) {
    return "本地写入命令没有完成。完整命令、权限审批和底层错误已保留在日志、回退记录和展开详情中。";
  }

  if (isControlledFullShellFailure(detail)) {
    return "本地高风险命令没有完成。完整命令、高风险确认、回退快照和底层错误已保留在日志、回退记录和展开详情中。";
  }

  if (isLocalRagFailure(detail)) {
    return "本地 RAG 没有完成。完整索引、解析器、文件路径和重试诊断已保留在日志、回退记录和展开详情中。";
  }

  if (isLocalExecutionMappingFailure(detail)) {
    return "本地助手返回了无法识别的执行结果。完整结果映射诊断已保留在日志、回退记录和展开详情中。";
  }

  if (isUnknownLocalExecutionFailure(detail)) {
    return "本地助手返回了空错误或未知错误。完整原始诊断已保留在日志、回退记录和展开详情中。";
  }

  return normalizeWorkbenchText(detail);
}

function getActionableOllamaFailureDetail(detail: string): string | null {
  const conciseDetail = stripLocalModelDiagnostics(detail);
  const normalized = conciseDetail.toLowerCase();
  const isActionableOllamaError =
    normalized.includes("ollama chat failed")
    || normalized.includes("ollama stream returned an error")
    || normalized.includes("no usable local ollama model")
    || (normalized.includes("model ") && normalized.includes("not found"));

  if (!isActionableOllamaError) {
    return null;
  }

  return `Ollama error: ${conciseDetail}`;
}

function stripLocalModelDiagnostics(detail: string): string {
  const diagnosticIndex = detail.indexOf("Local model chat diagnostics:");
  const conciseDetail = diagnosticIndex >= 0 ? detail.slice(0, diagnosticIndex) : detail;

  return conciseDetail.trim().replace(/[.\s]+$/, "");
}
